const RECAPTCHA_SECRET_KEY = process.env.RECAPTCHA_SECRET_KEY || ''
const BLOB_READ_WRITE_TOKEN = process.env.BLOB_READ_WRITE_TOKEN || ''
const PAYLOAD_SECRET = process.env.PAYLOAD_SECRET || ''
const DATABASE_URI = process.env.DATABASE_URI || ''
const PREVIEW_SECRET = process.env.PREVIEW_SECRET || ''
const RESEND_API_KEY = process.env.RESEND_API_KEY || ''
const RESEND_FROM_ADDRESS = process.env.RESEND_FROM_ADDRESS || ''

const NEXT_PUBLIC_RECAPTCHA_SITE_KEY = process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY || ''

export {
  BLOB_READ_WRITE_TOKEN,
  RECAPTCHA_SECRET_KEY,
  PAYLOAD_SECRET,
  DATABASE_URI,
  PREVIEW_SECRET,
  NEXT_PUBLIC_RECAPTCHA_SITE_KEY,
  RESEND_API_KEY,
  RESEND_FROM_ADDRESS,
}
